### ISSUE TITLE
Show-Stopper: Uncaught ReferenceError: Spacebars is not defined

### ISSUE THREAD

**Issue by krawalli** [aldeed/meteor-template-extension#24]
3.4.0 contains the missing underscore package bug. Please put a new release with the fix to atmosphere.

Please release new Package version.

**Comment by KrishnaPG** [comment]
This thing wasted me two days to figure out who the culprit was. 

After adding a new package to my project and did a casual `meteor update`, started seeing whole bunch of errors. All this while I was blaming the other new package and trying left and right somehow to identify / fix what was wrong with that package - just to realize after two days the culprit is this one. Wish they could test the packages at least once before releasing them to public.

Sorry to see after two days of the above complaint opening, still there is no fix for this - I am rolling back to older version for now

![image](https://cloud.githubusercontent.com/assets/4610831/6202491/bba5acb0-b514-11e4-9cd7-f0cbed19e3c4.png)

**Comment by mitar** [comment]
Yes, this was already merged. Just a new version has to be released.

**Comment by krawalli** [comment]
i did a workaround with having (git master) as local package and at least this error is gone. However i think there is a new problem, which i could not dive into yet.

the (Blaze) template created and rendered events (and so their function) are no longer triggered for sub-templates. My another workaround is to switch to this packages hooks. 

I did not isolate or tested and confirmed this. Maybe someone could test this and confirm everything is running before release the version.

**Comment by aldeed** [comment]
Released
