### ISSUE TITLE
Optimize code

### ISSUE THREAD

**Issue by aldeed** [aldeed/meteor-template-extension#41]
Abstract the wrappers that are similar where we check for array vs. template vs. template name.

**Comment by mitar** [comment]
> Use Blaze._getTemplate wherever we get template by name

For this you need also template instance. So I am not sure if it really works in this case. So this is useful when you are inside template rendering. Which is not so much how this package is used. (I realized later after I show you the method.)

**Comment by aldeed** [comment]
`templateInstance` arg isn't used. The comment says it's passed in in case someone wants to override the implementation.

**Comment by mitar** [comment]
It is used by Blaze Components. ;-) This is why this API was made like this. But you cannot really use this package to extend Blaze Components. But still, if you are using that function you should be providing template instance. Otherwise you are betting on internal implementation of it, that it currently does not use the second argument.

So at the definition time (so outside rendering) I think access `Template` directly is better. That method is more for during run-time, if you want to augment templates somehow.

**Comment by aldeed** [comment]
OK cool

**Comment by aldeed** [comment]
Closing. I don't think we'd gain much from abstracting this
